export type Phrase =
  | "Are you sure?"
  | "Cancel"
  | "Chat"
  | "Create a New Chat"
  | "Delete Chat"
  | "Delete"
  | "Deleted Chat with id"
  | "Deleting chat"
  | "End of Messages"
  | "Get the conversation started..."
  | "Invite a friend"
  | "Let's get you started by creating your first chat!"
  | "New Chat"
  | "No messages yet"
  | "Please wait while we delete the chat..."
  | "Send your first message in ANY language below to get started!"
  | "The AI will auto-detect & translate it all for you..."
  | "This will delete the chat for all users."
  | "Welcome!"
