import { Inter } from "next/font/google"

import { Header } from "@/components/Header"

import type { Metadata } from "next"

import "../styles/globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
