import { Inter } from "next/font/google"
import { Header } from "@/components/Header"
import { ThemeProvider } from "@/components/ThemeProvider"
import type { Metadata } from "next"

import "../styles/globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={inter.className}>
        <ThemeProvider
          enableSystem
          disableTransitionOnChange
          attribute="class"
          defaultTheme="dark"
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
